name: ctbc.com.cy
author: 'GRedneck'
title: 'Just a Greek that became a Redneck (and proud of it), trying to live a sustainable life.'
description: 'Just a Greek that became a Redneck (and proud of it), trying to live a sustainable life.'
keywords: 'sustainable living, living, debt free, financial tips, prepping tips'
tagline: G-Rednecks Unite!

url: https://gredneck.com
logo: /assets/img/gredneck-logo.png
social:
  name: GRedneck
  links:
    - https://t.me/g_redneck

#twitter:
#  username:
#  card: summary
#facebook:
#  app_id: 1234
#  publisher: 1234
#  admins: 1234
#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234
#lang: The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US.

google_analytics: ''

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages
  - _redirects

sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - serve
  - boxfile.yml
