backend:
  name: git-gateway
  branch: master

publish_mode: 'editorial_workflow'
media_folder: 'assets/files'  # Media files will be stored in the repo under assets/files

collections:
  - label: 'Strings'
    name: 'strings'
    files:
      - label: 'Settings'
        name: 'settings'
        file: '_data/settings.yml'
        fields:
          - {label: 'Text', name: 'text', widget: 'string'}
      - label: 'English'
        name: 'en'
        file: '_data/en.yml'
        fields:
          - {label: 'Text', name: 'text', widget: 'string'}
      - label: 'Russian'
        name: 'ru'
        file: '_data/ru.yml'
        fields:
          - {label: 'Text', name: 'text', widget: 'string'}
    create: true
